/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.BeansUsuario;
import modeloBeans.ModeloTabela;
import modeloConection.ConexaoBD;
import modeloDao.DaoUsuario;

/**
 *
 * @author Pinkman
 */
public class FormUsuario extends javax.swing.JFrame {

    BeansUsuario mod = new BeansUsuario();
    DaoUsuario dao = new DaoUsuario();
    ConexaoBD conex = new ConexaoBD();
    int flag = 0;
    public FormUsuario() {
        
        initComponents();
        //setSize(1920,1080);
        setLocation(530,150);
        
        preencherTabela("select * from usuario order by codigo_usuario");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCadastroUsuario = new javax.swing.JPanel();
        jLabelUsuCadUsu = new javax.swing.JLabel();
        jTextFieldUsuCadUsu = new javax.swing.JTextField();
        jLabelSenCadUsu = new javax.swing.JLabel();
        jPasswordFieldSenCadUsu = new javax.swing.JPasswordField();
        jLabelConfSenCadUsu = new javax.swing.JLabel();
        jPasswordFieldConfSenCadUsu = new javax.swing.JPasswordField();
        jLabelTipoCadUsu = new javax.swing.JLabel();
        jComboBoxTipoCadUsu = new javax.swing.JComboBox<>();
        jLabelConsCadastros = new javax.swing.JLabel();
        jLabelBuscCadUsu = new javax.swing.JLabel();
        jTextFieldBuscPesCadUsu = new javax.swing.JTextField();
        jButtonBuscUsuCadastrados = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListarUsuariosCadastrados = new javax.swing.JTable();
        jLabelUsuCodUsu = new javax.swing.JLabel();
        jTextFieldCodigoUsuario = new javax.swing.JTextField();
        jLabelIconFormularioCadUsu = new javax.swing.JLabel();
        jLabelTituloCadUsu = new javax.swing.JLabel();
        jButtonNovCadUsu = new javax.swing.JButton();
        jButtonEdiCadUsu = new javax.swing.JButton();
        jButtonExcCadUsu = new javax.swing.JButton();
        jButtonCanCadUsu = new javax.swing.JButton();
        jButtonSalvarCadUsu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelCadastroUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelUsuCadUsu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelUsuCadUsu.setText("Usuário:");

        jTextFieldUsuCadUsu.setEnabled(false);
        jTextFieldUsuCadUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuCadUsuActionPerformed(evt);
            }
        });

        jLabelSenCadUsu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSenCadUsu.setText("Senha:");

        jPasswordFieldSenCadUsu.setEnabled(false);
        jPasswordFieldSenCadUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldSenCadUsuActionPerformed(evt);
            }
        });

        jLabelConfSenCadUsu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelConfSenCadUsu.setText("Conf. Senha:");

        jPasswordFieldConfSenCadUsu.setEnabled(false);

        jLabelTipoCadUsu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTipoCadUsu.setText("Tipo:");

        jComboBoxTipoCadUsu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxTipoCadUsu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "administrador", "medico", "recepcionista", " " }));
        jComboBoxTipoCadUsu.setEnabled(false);
        jComboBoxTipoCadUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoCadUsuActionPerformed(evt);
            }
        });

        jLabelConsCadastros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelConsCadastros.setText("Consultar Cadastrados");
        jLabelConsCadastros.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabelBuscCadUsu.setText("Nome:");

        jButtonBuscUsuCadastrados.setText("Buscar");
        jButtonBuscUsuCadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscUsuCadastradosActionPerformed(evt);
            }
        });

        jTableListarUsuariosCadastrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableListarUsuariosCadastrados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListarUsuariosCadastradosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListarUsuariosCadastrados);

        jLabelUsuCodUsu.setText("Cod:");

        jTextFieldCodigoUsuario.setEnabled(false);
        jTextFieldCodigoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroUsuarioLayout = new javax.swing.GroupLayout(jPanelCadastroUsuario);
        jPanelCadastroUsuario.setLayout(jPanelCadastroUsuarioLayout);
        jPanelCadastroUsuarioLayout.setHorizontalGroup(
            jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanelCadastroUsuarioLayout.createSequentialGroup()
                .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroUsuarioLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelTipoCadUsu)
                            .addComponent(jLabelUsuCadUsu)
                            .addComponent(jLabelSenCadUsu)
                            .addComponent(jLabelConfSenCadUsu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordFieldSenCadUsu)
                            .addComponent(jComboBoxTipoCadUsu, 0, 226, Short.MAX_VALUE)
                            .addComponent(jTextFieldUsuCadUsu)
                            .addComponent(jPasswordFieldConfSenCadUsu)))
                    .addGroup(jPanelCadastroUsuarioLayout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jLabelConsCadastros)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelCadastroUsuarioLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabelUsuCodUsu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCodigoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(jLabelBuscCadUsu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBuscPesCadUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBuscUsuCadastrados)
                .addGap(213, 213, 213))
        );
        jPanelCadastroUsuarioLayout.setVerticalGroup(
            jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroUsuarioLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsuCadUsu)
                    .addComponent(jTextFieldUsuCadUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTipoCadUsu)
                    .addComponent(jComboBoxTipoCadUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSenCadUsu)
                    .addComponent(jPasswordFieldSenCadUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldConfSenCadUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelConfSenCadUsu))
                .addGap(40, 40, 40)
                .addComponent(jLabelConsCadastros)
                .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroUsuarioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelBuscCadUsu)
                            .addComponent(jTextFieldBuscPesCadUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBuscUsuCadastrados))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))
                    .addGroup(jPanelCadastroUsuarioLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelUsuCodUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCodigoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jLabelIconFormularioCadUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Botao_Formulario_01.png"))); // NOI18N

        jLabelTituloCadUsu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTituloCadUsu.setText("CADASTRO DE USUÁRIOS");

        jButtonNovCadUsu.setText("Novo");
        jButtonNovCadUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovCadUsuActionPerformed(evt);
            }
        });

        jButtonEdiCadUsu.setText("Editar");
        jButtonEdiCadUsu.setEnabled(false);
        jButtonEdiCadUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEdiCadUsuActionPerformed(evt);
            }
        });

        jButtonExcCadUsu.setText("Excluir");
        jButtonExcCadUsu.setEnabled(false);
        jButtonExcCadUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcCadUsuActionPerformed(evt);
            }
        });

        jButtonCanCadUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Botao_Cancelar_01.png"))); // NOI18N
        jButtonCanCadUsu.setEnabled(false);
        jButtonCanCadUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCanCadUsuActionPerformed(evt);
            }
        });

        jButtonSalvarCadUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Botao_Salvar_01.png"))); // NOI18N
        jButtonSalvarCadUsu.setEnabled(false);
        jButtonSalvarCadUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarCadUsuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(41, Short.MAX_VALUE)
                        .addComponent(jPanelCadastroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButtonNovCadUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEdiCadUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jButtonExcCadUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelIconFormularioCadUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTituloCadUsu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCanCadUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalvarCadUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelIconFormularioCadUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabelTituloCadUsu))
                                    .addComponent(jButtonCanCadUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jButtonSalvarCadUsu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonNovCadUsu)
                            .addComponent(jButtonEdiCadUsu)
                            .addComponent(jButtonExcCadUsu))
                        .addGap(8, 8, 8)))
                .addComponent(jPanelCadastroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        setSize(new java.awt.Dimension(852, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsuCadUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuCadUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuCadUsuActionPerformed

    private void jPasswordFieldSenCadUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldSenCadUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldSenCadUsuActionPerformed

    private void jButtonCanCadUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCanCadUsuActionPerformed
        // TODO add your handling code here:
        
        jTextFieldUsuCadUsu.setEnabled(!true);
        jComboBoxTipoCadUsu.setEnabled(!true);
        jPasswordFieldSenCadUsu.setEnabled(!true);
        jPasswordFieldConfSenCadUsu.setEnabled(!true);
        
        
        jTextFieldBuscPesCadUsu.setEnabled(true);
        jButtonBuscUsuCadastrados.setEnabled(true);
        
        jButtonCanCadUsu.setEnabled(false);
        jButtonNovCadUsu.setEnabled(true);
        jButtonSalvarCadUsu.setEnabled(false);
        jButtonEdiCadUsu.setEnabled(false);
        jButtonExcCadUsu.setEnabled(false);
        
        jTextFieldUsuCadUsu.setText("");
        //faltando o jComboBoxTipoCadUsu
        jPasswordFieldSenCadUsu.setText("");
        jPasswordFieldConfSenCadUsu.setText("");
        jTextFieldCodigoUsuario.setText("");
        
    }//GEN-LAST:event_jButtonCanCadUsuActionPerformed

    private void jButtonSalvarCadUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarCadUsuActionPerformed
        // TODO add your handling code here:

        if(jTextFieldUsuCadUsu.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe um USUÁRIO para continuar! ");
            jTextFieldUsuCadUsu.requestFocus();
        }//else if(jComboBoxTipoCadUsu.getToolTipText().isEmpty()){
            //JOptionPane.showMessageDialog(null, "Informe um TIPO para continuar! ");
            //jComboBoxTipoCadUsu.requestFocus();
        //}
        else if(jPasswordFieldSenCadUsu.getText().isEmpty()){
             JOptionPane.showMessageDialog(null, "Informe uma SENHA para continuar! ");
             jPasswordFieldSenCadUsu.requestFocus();
        }else if(jPasswordFieldConfSenCadUsu.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe a SENHA novamente para continuar! ");
            jPasswordFieldConfSenCadUsu.requestFocus();
        }else 
            
        if(jPasswordFieldSenCadUsu.getText().equals(jPasswordFieldConfSenCadUsu.getText())){//Confirmação de senha
          
        if(flag==1){
        mod.setNome_usuario(jTextFieldUsuCadUsu.getText());
        mod.setTipo_usuario((String)jComboBoxTipoCadUsu.getSelectedItem());
        mod.setSenha_usuario(jPasswordFieldSenCadUsu.getText());
        mod.setSenha_usuario(jPasswordFieldConfSenCadUsu.getText());
        
        dao.salvarUsuario(mod);
        
        jTextFieldBuscPesCadUsu.setText("");
        
        jTextFieldUsuCadUsu.setText("");
        jTextFieldUsuCadUsu.setEnabled(false);
        
        //jComboBoxTipoCadUsu.setToolTipText("");
        jComboBoxTipoCadUsu.setEnabled(false);
        
        jPasswordFieldSenCadUsu.setText("");
        jPasswordFieldSenCadUsu.setEnabled(false);
        
        jPasswordFieldConfSenCadUsu.setText("");
        jPasswordFieldConfSenCadUsu.setEnabled(false);
        
        jButtonSalvarCadUsu.setEnabled(false);
        jButtonCanCadUsu.setEnabled(false);
        jButtonNovCadUsu.setEnabled(true);
        
        jTextFieldBuscPesCadUsu.setEnabled(true);
        jButtonBuscUsuCadastrados.setEnabled(true);
        
        //tenho q preecher a tabela aq
        preencherTabela("select *from usuario order by codigo_usuario");
        }else{
        mod.setCodigo_usuario((Integer.parseInt(jTextFieldCodigoUsuario.getText())));
        mod.setNome_usuario(jTextFieldUsuCadUsu.getText());
        mod.setTipo_usuario((String)jComboBoxTipoCadUsu.getSelectedItem());
        mod.setSenha_usuario(jPasswordFieldSenCadUsu.getText());
        mod.setSenha_usuario(jPasswordFieldConfSenCadUsu.getText());
        
        dao.editarUsuario(mod);
        
        jTextFieldCodigoUsuario.setText("");
        
        jTextFieldBuscPesCadUsu.setText("");
        
        jTextFieldUsuCadUsu.setText("");
        jTextFieldUsuCadUsu.setEnabled(false);
        
        jComboBoxTipoCadUsu.setToolTipText("");
        jComboBoxTipoCadUsu.setEnabled(false);
        
        jPasswordFieldSenCadUsu.setText("");
        jPasswordFieldSenCadUsu.setEnabled(false);
        
        jPasswordFieldConfSenCadUsu.setText("");
        jPasswordFieldConfSenCadUsu.setEnabled(false);

        jButtonSalvarCadUsu.setEnabled(false);
        jButtonNovCadUsu.setEnabled(true);
        jButtonCanCadUsu.setEnabled(false);

        jTextFieldBuscPesCadUsu.setEnabled(true);
        jButtonBuscUsuCadastrados.setEnabled(true);
        //tenho q preecher a tabela aq
        preencherTabela("select * from usuario order by codigo_usuario");
        
        }
            
      }else{
            JOptionPane.showMessageDialog(rootPane, "Senhas não correspondem!");
            jButtonEdiCadUsu.setEnabled(false);
            jButtonExcCadUsu.setEnabled(false);
        }
       
    }//GEN-LAST:event_jButtonSalvarCadUsuActionPerformed

    private void jButtonNovCadUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovCadUsuActionPerformed
        // TODO add your handling code here:
        flag = 1;
        
        jTextFieldUsuCadUsu.setEnabled(true);
        jComboBoxTipoCadUsu.setEnabled(true);
        jPasswordFieldSenCadUsu.setEnabled(true);
        jPasswordFieldConfSenCadUsu.setEnabled(true);

        
        jButtonSalvarCadUsu.setEnabled(true);
        jButtonCanCadUsu.setEnabled(true);
                
        jTextFieldUsuCadUsu.setText("");
        jComboBoxTipoCadUsu.setToolTipText("");
        jPasswordFieldSenCadUsu.setText("");
        jPasswordFieldConfSenCadUsu.setText("");
        
        
        jButtonEdiCadUsu.setEnabled(false);
        jButtonExcCadUsu.setEnabled(false);
        jTextFieldBuscPesCadUsu.setEnabled(false);
        jButtonBuscUsuCadastrados.setEnabled(false);
        jButtonNovCadUsu.setEnabled(false);
        
        jTextFieldBuscPesCadUsu.setText("");
        
    }//GEN-LAST:event_jButtonNovCadUsuActionPerformed

    private void jButtonEdiCadUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEdiCadUsuActionPerformed
        // TODO add your handling code here:
            
        flag = 2;
        
        jTextFieldUsuCadUsu.setEnabled(true);
        jComboBoxTipoCadUsu.setEnabled(true);
        jPasswordFieldSenCadUsu.setEnabled(true);
        jPasswordFieldConfSenCadUsu.setEnabled(true);
        
        jButtonCanCadUsu.setEnabled(true);
        jButtonSalvarCadUsu.setEnabled(true);
        jButtonNovCadUsu.setEnabled(false);
        jButtonEdiCadUsu.setEnabled(false);
        jButtonExcCadUsu.setEnabled(false);
        preencherTabela("select *from usuario order by codigo_usuario");
    }//GEN-LAST:event_jButtonEdiCadUsuActionPerformed

    private void jButtonExcCadUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcCadUsuActionPerformed
        // TODO add your handling code here:
        
        int resp = 0;
        resp = JOptionPane.showConfirmDialog(rootPane, "Deseja Realmente Excluir? ");
        if(resp== JOptionPane.YES_OPTION){
            mod.setCodigo_usuario(Integer.parseInt(jTextFieldCodigoUsuario.getText())); //TALVEZ DE PROBLEMA
            dao.excluirUsuario(mod);
            
            jButtonExcCadUsu.setEnabled(false);
            jButtonEdiCadUsu.setEnabled(false);
            jButtonSalvarCadUsu.setEnabled(false);
            jButtonCanCadUsu.setEnabled(false);
            jButtonNovCadUsu.setEnabled(true);
            
            //Limpar e desativar novamente
            jTextFieldBuscPesCadUsu.setText("");
            jTextFieldCodigoUsuario.setText("");
            
            jTextFieldUsuCadUsu.setText("");
            jTextFieldUsuCadUsu.setEnabled(false);
            
            
            jComboBoxTipoCadUsu.setEnabled(false);//FALTA LIMPAR
            
            jPasswordFieldSenCadUsu.setText("");
            jPasswordFieldSenCadUsu.setEnabled(false);
            
            jPasswordFieldConfSenCadUsu.setText("");
            jPasswordFieldConfSenCadUsu.setEnabled(false);
            
            
            preencherTabela("select * from usuario order by codigo_usuario");
            
        }
        
        
    }//GEN-LAST:event_jButtonExcCadUsuActionPerformed

    public void preencherTabela(String sql){
        ArrayList dados  = new ArrayList();
        String [] colunas = new String[] {"Id","Usuario","Tipo","Senha"};
                
        conex.conectarPostgre();
        conex.executarSql(sql);
        
        try {
            conex.rs.first();
            
            do{
                dados.add(new Object[]{conex.rs.getString("codigo_usuario"),conex.rs.getString("nome_usuario"), conex.rs.getString("tipo_usuario"), conex.rs.getString("senha_usuario")});
            }while(conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Busco por outro Usuário para preencher Tabela! " + ex);
        }
        ModeloTabela modelousuario = new ModeloTabela(dados, colunas);
        
        jTableListarUsuariosCadastrados.setModel(modelousuario);
        jTableListarUsuariosCadastrados.getColumnModel().getColumn(0).setPreferredWidth(2);
        jTableListarUsuariosCadastrados.getColumnModel().getColumn(0).getResizable();
        jTableListarUsuariosCadastrados.getColumnModel().getColumn(1).setPreferredWidth(220);
        jTableListarUsuariosCadastrados.getColumnModel().getColumn(1).getResizable();
        jTableListarUsuariosCadastrados.getColumnModel().getColumn(2).setPreferredWidth(80);
        jTableListarUsuariosCadastrados.getColumnModel().getColumn(2).getResizable();
        
        jTableListarUsuariosCadastrados.getColumnModel().getColumn(3).setPreferredWidth(8);
        jTableListarUsuariosCadastrados.getColumnModel().getColumn(3).getResizable();
        

        jTableListarUsuariosCadastrados.getTableHeader().setReorderingAllowed(false);
        
        //jTableListarUsuariosCadastrados.setAutoResizeMode(jTableListarUsuariosCadastrados.AUTO_RESIZE_ALL_COLUMNS);
        
        jTableListarUsuariosCadastrados.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        conex.desconectar();
    }
    
    private void jTableListarUsuariosCadastradosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListarUsuariosCadastradosMouseClicked
        // TODO add your handling code here:
        String nome_usuario =""+jTableListarUsuariosCadastrados.getValueAt(jTableListarUsuariosCadastrados.getSelectedRow(), 1);
        
        conex.conectarPostgre();
        
        conex.executarSql("select * from usuario where nome_usuario='"+nome_usuario+"'");
        try {
            conex.rs.first();
            
            jTextFieldCodigoUsuario.setText(String.valueOf(conex.rs.getInt("codigo_usuario")));
            jTextFieldUsuCadUsu.setText(conex.rs.getString("nome_usuario"));
            jComboBoxTipoCadUsu.setSelectedItem(conex.rs.getString("tipo_usuario"));
            jPasswordFieldSenCadUsu.setText(conex.rs.getString("senha_usuario"));
            jPasswordFieldConfSenCadUsu.setText(conex.rs.getString("senha_usuario"));
                
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar dados do Usuário! "+ex);
        }
        conex.desconectar();
        jButtonEdiCadUsu.setEnabled(true);
        jButtonExcCadUsu.setEnabled(true);
        jButtonNovCadUsu.setEnabled(false);
        jButtonCanCadUsu.setEnabled(true);
    }//GEN-LAST:event_jTableListarUsuariosCadastradosMouseClicked

    
    
    private void jComboBoxTipoCadUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoCadUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoCadUsuActionPerformed

    public void geral(){
        jTextFieldUsuCadUsu.setEnabled(true);
        jComboBoxTipoCadUsu.setEnabled(true);
        jPasswordFieldSenCadUsu.setEnabled(true);
        jPasswordFieldConfSenCadUsu.setEnabled(true);
    }
    private void jButtonBuscUsuCadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscUsuCadastradosActionPerformed
        // TODO add your handling code here:
        
        mod.setPesquisa_Usuario(jTextFieldBuscPesCadUsu.getText());
        BeansUsuario model = dao.buscarUsuario(mod);
        
       
        jTextFieldCodigoUsuario.setText(String.valueOf(model.getCodigo_usuario()));
        jTextFieldUsuCadUsu.setText(model.getNome_usuario());
        jComboBoxTipoCadUsu.setSelectedItem(model.getTipo_usuario());
        jPasswordFieldSenCadUsu.setText(model.getSenha_usuario());
        jPasswordFieldConfSenCadUsu.setText(model.getSenha_usuario());
        
        jButtonEdiCadUsu.setEnabled(false);
        //jButtonSalvarCadUsu.setEnabled(true);
        jButtonExcCadUsu.setEnabled(false);
        jButtonNovCadUsu.setEnabled(false);
        jButtonCanCadUsu.setEnabled(true);
        //jTextFieldBuscPesCadUsu.setText("");
        preencherTabela("select * from usuario where nome_usuario like'%"+mod.getPesquisa_Usuario()+"%'");
        
    }//GEN-LAST:event_jButtonBuscUsuCadastradosActionPerformed

    private void jTextFieldCodigoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscUsuCadastrados;
    private javax.swing.JButton jButtonCanCadUsu;
    private javax.swing.JButton jButtonEdiCadUsu;
    private javax.swing.JButton jButtonExcCadUsu;
    private javax.swing.JButton jButtonNovCadUsu;
    private javax.swing.JButton jButtonSalvarCadUsu;
    private javax.swing.JComboBox<String> jComboBoxTipoCadUsu;
    private javax.swing.JLabel jLabelBuscCadUsu;
    private javax.swing.JLabel jLabelConfSenCadUsu;
    private javax.swing.JLabel jLabelConsCadastros;
    private javax.swing.JLabel jLabelIconFormularioCadUsu;
    private javax.swing.JLabel jLabelSenCadUsu;
    private javax.swing.JLabel jLabelTipoCadUsu;
    private javax.swing.JLabel jLabelTituloCadUsu;
    private javax.swing.JLabel jLabelUsuCadUsu;
    private javax.swing.JLabel jLabelUsuCodUsu;
    private javax.swing.JPanel jPanelCadastroUsuario;
    private javax.swing.JPasswordField jPasswordFieldConfSenCadUsu;
    private javax.swing.JPasswordField jPasswordFieldSenCadUsu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListarUsuariosCadastrados;
    private javax.swing.JTextField jTextFieldBuscPesCadUsu;
    private javax.swing.JTextField jTextFieldCodigoUsuario;
    private javax.swing.JTextField jTextFieldUsuCadUsu;
    // End of variables declaration//GEN-END:variables
}
